apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ghcr.io/PLACEHOLDER/nginx-release
    newTag: qa_latest

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: nginx-release
