apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-release
  namespace: release-app
spec:
  replicas: 1
  template:
    spec: # nosemgrep: yaml.kubernetes.security.run-as-non-root.run-as-non-root
      containers:
        - name: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu:    "50m"
            limits:
              memory: "128Mi"
              cpu:    "100m"
